#!/bin/sh

branch=$2

rm -f fileadmin/website_files/ts/domain.ts
rm -f typo3conf/LocalConfiguration.php
rm -f typo3conf/PackageStates.php

ln -s ../../typo3_src/index.php index.php
ln -s ../../typo3_src/typo3 typo3
ln -s ../../uploads uploads
ln -s ../../../medien fileadmin/medien

cp -f .deploy/${branch}/LocalConfiguration.php typo3conf/LocalConfiguration.php
cp -f .deploy/${branch}/PackageStates.php typo3conf/PackageStates.php
cp -f .deploy/${branch}/domain.ts fileadmin/website_files/ts/domain.ts
cp -f .deploy/${branch}/.htaccess .htaccess
cp -f .deploy/${branch}/.htpasswd .htpasswd

mkdir typo3temp
mkdir typo3temp/_processed_

chown www-data:www-data -R .